site_name: Jonas Beyer
site_description: Jonas Beyer's blog
site_url: https://jonbyr.com
repo_name: Gizzzzmo/blog
repo_url: https://github.com/Gizzzzmo/blog
docs_dir: content
plugins:
  - obsidian-bridge
  - search
  # - rss
markdown_extensions:
  - obsidian_media_mkdocs
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - mdx_math

theme:
  name: simple-blog

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - js/extra.js
copyright: Jonas Beyer

#extra:
#  social:
#    - name: github
#      icon: https://github.com/FernandoCelmer/mkdocs-simple-blog/raw/refs/heads/master/docs/assets/favicon.ico
#      link: https://github.com/Gizzzzmo

